### PR TITLE
TOC changes, stubbed out areas (more to come), and Content Requirements

### PR DESCRIPTION
**Pull request by quinnelton**
Updated the TOC a bit, went with Create, Test, Submit as the high-level folders.
Added our Content Requirements for everything.

### CODE REVIEW

**Comment by mattwojo** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[minecraft-marketplace/create/durable-content-requirements.md](https://github.com/MicrosoftDocs/minecraft-marketplace/blob/quinn-dev/minecraft-marketplace/create/durable-content-requirements.md) | :warning:Warning | | [Details](#user-content-minecraft-marketplace%2Fcreate%2Fdurable-content-requirements.md)
[minecraft-marketplace/create/server-content-requirements.md](https://github.com/MicrosoftDocs/minecraft-marketplace/blob/quinn-dev/minecraft-marketplace/create/server-content-requirements.md) | :warning:Warning | | [Details](#user-content-minecraft-marketplace%2Fcreate%2Fserver-content-requirements.md)
[minecraft-marketplace/index.md](https://github.com/MicrosoftDocs/minecraft-marketplace/blob/quinn-dev/minecraft-marketplace/index.md) | :warning:Warning | | [Details](#user-content-minecraft-marketplace%2Findex.md)
[minecraft-marketplace/TOC.md](https://github.com/MicrosoftDocs/minecraft-marketplace/blob/quinn-dev/minecraft-marketplace/TOC.md) | :white_check_mark:Succeeded | |
[minecraft-marketplace/publish-content.md](https://github.com/MicrosoftDocs/minecraft-marketplace/blob/quinn-dev/minecraft-marketplace/publish-content.md) | :white_check_mark:Succeeded | |
[minecraft-marketplace/submission/submission-process.md](https://github.com/MicrosoftDocs/minecraft-marketplace/blob/quinn-dev/minecraft-marketplace/submission/submission-process.md) | :white_check_mark:Succeeded | |
[minecraft-marketplace/submit-content.md](https://github.com/MicrosoftDocs/minecraft-marketplace/blob/quinn-dev/minecraft-marketplace/submit-content.md) | :white_check_mark:Succeeded | |
[minecraft-marketplace/test-content.md](https://github.com/MicrosoftDocs/minecraft-marketplace/blob/quinn-dev/minecraft-marketplace/test-content.md) | :white_check_mark:Succeeded | |
[minecraft-marketplace/test/validation-tool.md](https://github.com/MicrosoftDocs/minecraft-marketplace/blob/quinn-dev/minecraft-marketplace/test/validation-tool.md) | :white_check_mark:Succeeded | |

<a name="minecraft-marketplace%2Fcreate%2Fdurable-content-requirements.md"></a>
### [minecraft-marketplace/create/durable-content-requirements.md](https://github.com/MicrosoftDocs/minecraft-marketplace/blob/quinn-dev/minecraft-marketplace/create/durable-content-requirements.md)
 - **[Warning]** Author shawjohn, quinnelton cannot be recognized in GitHub.

<a name="minecraft-marketplace%2Fcreate%2Fserver-content-requirements.md"></a>
### [minecraft-marketplace/create/server-content-requirements.md](https://github.com/MicrosoftDocs/minecraft-marketplace/blob/quinn-dev/minecraft-marketplace/create/server-content-requirements.md)
 - **[Warning]** Author shawjohn, quinnelton cannot be recognized in GitHub.

<a name="minecraft-marketplace%2Findex.md"></a>
### [minecraft-marketplace/index.md](https://github.com/MicrosoftDocs/minecraft-marketplace/blob/quinn-dev/minecraft-marketplace/index.md)
 - **Line 0**: **[Warning]** Invalid file link:(~/create-content).
 - **Line 0**: **[Warning]** Invalid file link:(~/test-content).
 - **Line 0**: **[Warning]** Invalid file link:(~/get-started).
 - **Line 0**: **[Warning]** Invalid file link:(~/submit-content).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C16%5Cb1c7400c-ce33-0fc1-29a2-3e715f040480%5CPullRequest%5C201706160202230507-1%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by quinnelton** [comment]
Ah, was hoping you could do multiple authors, but it looks like it automatically adds them to the page based on who's changed the file.

@mattwojo Do those links in the index need to be changed to have a '.md' at the end?

**Comment by mattwojo** [comment]
@quinnelton - Yes, the links need a .md and you're right that the system automatically adds authors based on who has changed the file. Manually entering multiple authors with a comma doesn't work. :(  Just as a reference if you're interested, this page explains what all the metadata fields are and a bit about how they can be used: https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-metadata?branch=master

**Comment by mattwojo** [comment]
Oh and my general recommendation is to have the main author who 'owns' the content listed in the metadata -- translation: whoever is on point to answer questions about the content or make updates based on requests. 💯

**Pull request merged**
